- name: Desplegar infraestructura completa
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Ejecutar role common
      ansible.builtin.include_role:
        name: common

    - name: Ejecutar role asdf
      ansible.builtin.include_role:
        name: cimon-io.asdf

    - name: Cambiar dueño del directorio .asdf (justo después del role asdf)
      ansible.builtin.file:
        path: /home/redmine/.asdf
        state: directory
        recurse: true
        owner: redmine
        group: redmine

    - name: Ejecutar role geerlingguy.mysql
      ansible.builtin.include_role:
        name: geerlingguy.mysql

    - name: Descargar e instalar redmine
      ansible.builtin.include_role:
        name: redmine

    - name: Ejecutar role geerlingguy.nginx
      ansible.builtin.include_role:
        name: geerlingguy.nginx
