[project]
name = "redmine-ansible"
version = "0.1.0"
description = ""
authors = [
    {name = "Martin",email = "martin.rodriguez@mikroways.net"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible (>=11.0.0,<11.1.0)",
    "molecule-plugins[docker] (>=23.7.0,<24.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
