- name: Instalar dependencias base
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - libmariadb-dev
      - git
      - coreutils
      - libffi-dev
      - libedit-dev
      - libyaml-dev
      - unzip
      - curl
      - sudo
    update_cache: yes

- name: Crear grupo redmine
  group:
    name: "{{ redmine_group }}"
    state: present

- name: Crear usuario redmine
  user:
    name: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    shell: /bin/bash
    create_home: yes

- name: Agregar vagrant al grupo redmine
  user:
    name: "{{ vagrant_user }}"
    groups: "{{ redmine_group }}"
    append: yes
