- name: Instalar dependencias base
  ansible.builtin.apt:
    name:
      - build-essential
      - zlib1g-dev
      - git
      - coreutils
      - libffi-dev
      - libedit-dev
      - libyaml-dev
      - unzip
      - curl
      - sudo
      - ruby-dev
      - libmysqlclient-dev
    update_cache: true

- name: Crear usuario redmine
  ansible.builtin.user:
    name: "{{ redmine_user }}"
    shell: /bin/bash
    create_home: true
